const dogRaceList = [
    { label: 'Akita Inu', value: 'Akita Inu' },
    { label: 'Basset Hound', value: 'Basset Hound' },
    { label: 'Basenji', value: 'Basenji' },
    { label: 'Beagle', value: 'Beagle' },
    { label: 'Berger Allemand', value: 'Berger Allemand' },
    { label: 'Berger Australien', value: 'Berger Australien' },
    { label: 'Berger Belge Malinois', value: 'Berger Belge Malinois' },
    { label: 'Berger des Shetland', value: 'Berger des Shetland' },
    { label: 'Bichon Frisé', value: 'Bichon Frisé' },
    { label: 'Bouledogue Anglais', value: 'Bouledogue Anglais' },
    { label: 'Bouledogue Français', value: 'Bouledogue Français' },
    { label: 'Boxer', value: 'Boxer' },
    { label: 'Cairn Terrier', value: 'Cairn Terrier' },
    { label: 'Caniche', value: 'Caniche' },
    { label: 'Cavalier King Charles', value: 'Cavalier King Charles' },
    { label: 'Chihuahua', value: 'Chihuahua' },
    { label: 'Chow-Chow', value: 'Chow-Chow' },
    { label: 'Colley à poil long', value: 'Colley à poil long' },
    { label: 'Cocker Spaniel Anglais', value: 'Cocker Spaniel Anglais' },
    { label: 'Dalmatien', value: 'Dalmatien' },
    { label: 'Dobermann', value: 'Dobermann' },
    { label: 'Dogue Allemand', value: 'Dogue Allemand' },
    { label: 'Epagneul Breton', value: 'Epagneul Breton' },
    { label: 'Epagneul Japonais', value: 'Epagneul Japonais' },
    { label: 'Epagneul Papillon', value: 'Epagneul Papillon' },
    { label: 'Fox Terrier', value: 'Fox Terrier' },
    { label: 'Golden Retriever', value: 'Golden Retriever' },
    { label: 'Grand Caniche', value: 'Grand Caniche' },
    { label: 'Griffon Bruxellois', value: 'Griffon Bruxellois' },
    { label: 'Hovawart', value: 'Hovawart' },
    { label: 'Husky Sibérien', value: 'Husky Sibérien' },
    { label: 'Jack Russell Terrier', value: 'Jack Russell Terrier' },
    { label: 'Kangal', value: 'Kangal' },
    { label: 'Labrador Retriever', value: 'Labrador Retriever' },
    { label: 'Lévrier Afghan', value: 'Lévrier Afghan' },
    { label: 'Mastiff', value: 'Mastiff' },
    { label: 'Petit Lévrier Italien', value: 'Petit Lévrier Italien' },
    { label: 'Pinscher Nain', value: 'Pinscher Nain' },
    { label: 'Rottweiler', value: 'Rottweiler' },
    { label: 'Saint-Bernard', value: 'Saint-Bernard' },
    { label: 'Samoyède', value: 'Samoyède' },
    { label: 'Schipperke', value: 'Schipperke' },
    { label: 'Setter Irlandais', value: 'Setter Irlandais' },
    { label: 'Shar Pei', value: 'Shar Pei' },
    { label: 'Shiba Inu', value: 'Shiba Inu' },
    { label: 'Shih Tzu', value: 'Shih Tzu' },
    { label: 'Spitz Nain', value: 'Spitz Nain' },
    { label: 'Teckel', value: 'Teckel' },
    { label: 'Terre-Neuve', value: 'Terre-Neuve' },
    { label: 'West Highland White Terrier', value: 'West Highland White Terrier' },
    { label: 'Whippet', value: 'Whippet' },
    { label: 'Yorkshire Terrier', value: 'Yorkshire Terrier' }
];


export default dogRaceList;